name: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - homolog

jobs:
  version:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Set branch name
        run: |
          echo "RELEASE_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necessário para ler todo o histórico de commits e tags

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Calculate Next Version
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Executa o dry-run e captura o log
          OUTPUT=$(npx semantic-release --dry-run)
          
          # Extrai a versão do log (procura por "The next release version is X.Y.Z")
          NEXT_VERSION=$(echo "$OUTPUT" | grep -oP 'next release version is \K[0-9]+\.[0-9]+\.[0-9]+[^\s]+')
          
          if [ -z "$NEXT_VERSION" ]; then
            echo "Nenhuma mudança semântica detectada. Pulando tag."
            echo "new_release_published=false" >> $GITHUB_OUTPUT
          else
            echo "Proxima versão: $NEXT_VERSION"
            echo "next_version=$NEXT_VERSION" >> $GITHUB_OUTPUT
            echo "new_release_published=true" >> $GITHUB_OUTPUT
          fi

      - name: Create and Push Tag Manually
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          NEXT_TAG="v${{ steps.semantic.outputs.next_version }}"
          
          echo "Criando tag $NEXT_TAG..."
          git tag $NEXT_TAG
          git push origin $NEXT_TAG