name: versioning

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - homolog

jobs:
  version:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Set branch name
        run: |
          echo "RELEASE_BRANCH=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install semantic-release
        run: npm install -g semantic-release @semantic-release/commit-analyzer

      - name: Calculate next version (dry-run)
        id: version
        run: |
          NEXT_VERSION=$(semantic-release --dry-run \
            --plugins @semantic-release/commit-analyzer \
            | grep -oP 'next release version is \K[0-9]+\.[0-9]+\.[0-9]+')

          echo "next=$NEXT_VERSION" >> $GITHUB_OUTPUT
      
      - uses: actions/checkout@v3
      - name: Create Tag
        run: |
          DEPLOY_VERSION="v${{ steps.version.outputs.next }}"
          sudo chmod 666 /dev/null
          if [ -z $(git rev-parse -q --verify "$DEPLOY_VERSION") > /dev/null 2>&1 ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git tag "$DEPLOY_VERSION" "$GITHUB_SHA"
            git push origin "$DEPLOY_VERSION"
          else
            echo "Tag $DEPLOY_VERSION exists locally."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}